directories:
  backend:
    - /home/orestes/Workspace/src/github.com/moreorem/graphdener-backend/target/debug/
constants:
  alg:
    - 'rand uniform'
    - 'rand normalized'
    - 'circular'
    - 'force directed'
  forcelabels:
    - 'Spring rest length'
    - 'Repulsive force constant'
    - 'Spring constant'
    - 'Time step'
  # Mandatory columns should not be changed. These include id, type, from, to.
  # The user may add extra columns the data of which is considered metadata 
  nodecnames:
    - 'n_id'
    - 'n_label'
    - 'n_type'
  edgecnames:
    - 'e_id'
    - 'e_from'
    - 'e_to'
    - 'e_label'
    - 'e_type'
    - 'e_weight'
  columntypes:
    {
      'n_id': 'int',
      'n_label': 'str',
      'n_type': 'str',
      'e_weight': 'int',
      'e_from': 'int',
      'e_to': 'int',
      '-': '',
      'e_id': 'int',
      'e_label': 'str',
      'e_type': 'str'
    }
# User may change graph options such as marker/arrow size and framerate limiter
graph:
  marker_size: 40
  arrow_size: 0.05
  framecap: 60
importer:
  acceptedsymbols: :.()&'-