directories:
  backend:
    - /home/orestes/Workspace/src/github.com/moreorem/graphdener-backend/target/debug/
  export:
    - \path\to\xml\upload\ # resources\export\

constants:
  alg:
    - 'random'
    - 'circular'
    - 'force directed'
  forcelabels:
    - 'Spring rest length'
    - 'Repulsive force constant'
    - 'Spring constant'
    - 'Time step'
  nodecnames:
    - 'n_id'
    - 'n_label'
    - 'n_type'
  edgecnames:
    - 'e_id'
    - 'e_from'
    - 'e_to'
    - 'e_label'
    - 'e_type'
    - 'e_weight'
  columntypes:
    {
      'n_id': 'int',
      'n_label': 'qstr',
      'n_type': 'qstr',
      'e_weight': 'int',
      'e_from': 'int',
      'e_to': 'int',
      '-': '',
      'e_id': 'int',
      'e_label': 'qstr',
      'e_type': 'qstr'
    }
graph:
  marker:
    - size: 20
  edge: