directories:
  backend:
    - /home/orestes/Workspace/src/github.com/moreorem/graphdener-backend/target/debug/
  export:
    - \path\to\xml\upload\ # resources\export\

constants:
  alg:
    - 'random'
    - 'circular'
    - 'force directed'
  forcelabels:
    - 'Spring rest length'
    - 'Repulsive force constant'
    - 'Spring constant'
    - 'Time step'
  nodecnames:
    - 'n_id'
    - 'n_label'
    - 'n_type'
  edgecnames:
    - 'e_id'
    - 'from'
    - 'to'
    - 'e_label'
    - 'e_type'
    - 'weight'

graph:
  marker:
    - size: 20
  edge: